language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew build"
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    repo: hmcts/sscs-pdf-robotics-email-common
    tags: true
- provider: releases
  api_key:
    secure: vY+rGfzlyod6M3oeRqE6B1guipKB9aZ6xCWihD0B2Gwe27GZRtiJhiUjqApakIy0j/yB61bosKSAa8c98I/zv3dK7dsXPS7i0EsDYFC567oAv3t4vp4mZxemzri0R3ONvL/8UFu8mXZmHqbDH4FaMjQOSy+CPkYu3ns++zgxvC38zeeoXj0hG7GDbYudSFJPm/ABgK0cE4D2ePrMcQgciY+hJLvGeUdgvw2Mz5XnZXwpausInLql1GftOynlFtwNSe/y2j1cA01LEZTjAed+7bg5h5E2OAPiwdE+UvZ3IV2vHCu5fgir4wWw8kbQtrlqJkMHJ6cYQt3Lcl3dG04Z32aiVAhV7Imub7J3oWVXhNsk72A1GVTVo2aXAuApbKTvs+AB3PwczGXRQFhZoibdQCUND20PibOsYxyW7/jWCVd7gc/Lz1mNaensnPn2MqgWTsv6c4sLwx7XkFbVPpFCQKRVGTUumAyIAj0UBCddaKqTrQzoAr1xCYDIigRlfYdlEXVUP00rpAGOeLm6Uxmh7qF+9nmWJ3d5HLSi6r7LmOe1DgyZmMFqIHW2IFbyleWTT7YVsJ3XMNVxWaQv9XFHw+/qXLLw85QTK6LjbPbLBAoWaqMkx/yqkSW+ZWlf/tG24OQMs1VyrAElmrUmSj0YFolRhNfahdkepNlHMw9YQ7k=
  file: build/libs/sscs-pdf-robotics-email-common-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: hmcts/sscs-pdf-robotics-email-common
    tags: true
env:
  global:
  - secure: Jy0iC9MHwqU0FE06FTY5SVqb6KV4mQuWNxyjx/OT6qJoEKqqZDoGQLymv919MSebQRtneAjaYwA399u45tRnOIKYYp/kA6oisNeNWKuhyAygDKnc9A6lxYYW5eS3wiCOfFHBy5rP9L+q5PWYMP9+aGnU9XpIPTUMmv/etRjDbVlvbwH623F/v/UiBcEH5ynKGM3vyPk94Vwk9P5r32as24Mk6gZZ+KzdILRlWIXYwsxpw2IWseCTZ0/muDW10CXduXslW5nc4dhLz1aRpf7TXATQHHbCcxDtsvsQtjkYGPe1clNPJyIB2p7d3iFsEG8Gg1UYBC9WbSLLA7E7DGMtIFJ8mqKbMe3IYqHAZ410wgKxEWkCsU7my972YsoqKIdWGogCO61iryEo3SzpBdvNSqykl1Tvhbqa87awl4upj+r1N4iVf9QYkiSHwm7LbRYDjBYR/YIgbIsUmbfLAsoadbIuct0yTasMgPNepSdQOHBQ7HsUrYR4LutgSr8puOGkGXWF3JHXuP4hOtnr9fYYC3d9hf+8Ve16EzSeulwt5iHbVCDjz+ADrZXGme19CUASNUf/ITj+3TR+BkQBUR1OHCqOYclTzRcBiejiA7aUwWU5PK7Fhs9QvHK8lCOLz4zVkgwKfqqZEu3bYVHx8VNp/3y6ou5mEnaCytKOujIGDeg=
  - secure: WS2pbLYL1TLOnQRpU2+/2htoqigOa7vfF8tNzFGAtkJDyLaFDkdRZtym+Y/9s/xtOc+InmZuVSD89AgJvttfv8I3VyzQc1xLJR7AwXdgMsSnjhwN1WRXZbz8exWqVgIqIz2LzItY6Fw+hRP9zoQLcg812lIrGyE9avOzgxZIPCkS0fZyhWd25/lZRqSDAGBX2Qsgwdj7NHI5L0+HogqbiPfBn+ycl1qTMl8rCnenWMH7owYY11aoQN6Nfh2orPcw0icpD20OOlcgXVU0afz9I8+XLly+vgAyQZfknol6Iqa72gt9vr+/SVt7YtWZ4w3GS6LzE4Bbll8uohYqZ0DW3krmNhmyoIGPDkgbNm+524H8LA5MmJPQDE4L8iKvGZodjyHJx150V5rzN0fLYE/OhJeNzDwx33Xsx0f4RXGaAIjqcmUaWwNtJF3L+9V6YvLG8PuLxo/fXXbrC/3vd+wyU+lCsW8U+/DsRNpCXFcN2yU/A+kFO2YXjMWNKJvFb+eEBpiyxQknJ2BDthV4Bk9LEXd6MwOIE4TgJaUeJAOwn+UAWFMcQDb+PKqwD5MjJnzche+nYPLb2bD0kDRiPKA/mgBlLQHMCvgfe7JIYFFnFqgmZlJlrx8m5HXx5C7ALi2Dz4ZX9SI+me2TN6QmofSQdj3Q5v42d01gSwCicWnrtnA=
