language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew build"
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    repo: hmcts/sscs-pdf-robotics-email-common
    branch: master
- provider: releases
  file: build/libs/sscs-pdf-robotics-email-common-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: hmcts/sscs-pdf-robotics-email-common
    tags: true
env:
  global:
  - secure: dt77cAPWRD/JnQLtyqeeS6e/BUmw4gM1uM9tED7ID586TUsomoX3axmyi8Rm4EnClN2FvlkqXiJCLfvNz8omobN9LLBYIHGepu2QvuZEZ81bsBU6qLvqkt72O2LJOS7+Cyc4TL7fdGdO3mKwp5serabYglC5iLLtRd/LDeYYPbpvfbzaY/BmwJSpYHrak2d0cMMQz/WHFVzTPuBenG+QwwPT+SBsV9EeuVrkticSc7eMjQUOMC00WYdjs2mw76dp5bXAF5yD7u/2s/1HOCE5AEmkGwRBvhCIOZKWU8icRUS8ywmKbjuhtdf4xqJqlTrUm/ZClh2x/mAS4gG8Q8piGPY8g0tSqmHdpB5kTpGsNEGC1SCqSBTpx0UUCbDwUHkBsZ2XbrI6//nCFWoJHpbezWE/n2au6tf84KAwyTo/RYToms2eX+tE22ZlSQt5iDXcKMmDJ1Uta2oUN4WHngP807xWiuntdSVhtOPC5IRecTSwaOEBetHJ5jpBt22kNLTii+C5p5D5zhqiRAC0Ye5eVcFqPGl7djn2hb5Vtf+F4X0HsF2AdaIam9ERjX5iMB/hJ+jxuTPDVAYN9/1dlrv1SXUBMC9lOx5XdGmAt4XZk+Dej9FaYBLhZ1XWgNVt6VCmjWGaBwanvsycoH1FnNyl8mfM521m45o0gB/jjKNpjds=
  - secure: VKxiZcOqLnEseAJ7comg+BR3wg/JF1nPqf79dSF0Za1a9ZiI/0VSTcPbrNH/8zpIjaJJuiqVmEzh7nIkiHpwE/IRlTablGbEupS8V2X30bGO0nKTeDOZ61ne5u8vl6JWhnqoQqvd8mMLrKUqboN7EYUYpilLoiciVLRVfruq3Jhmnyuiztw4EAiJCaJQ2yf37YCM7GJJU8SedHoAcO1sH4Ezzp5IpSexwTZulZk+Rek7BsnKQH3cOsGdCltMxvwY4nJV+1V9854E2QuardkgNv7i1Re7Jx7/dKsp65PLkmbR5M65JbyM7i4I/hZcPMgBu9RK6U+TMlfPYMYI+zOhN6cRSuFnO2sda8HoS3IewyMxlWgngC4scC6Ox1oW/pVdgpf5ABbMqo6+I/3da1eK+47rZ7jt5Pj5Jicrk35h47W6hHXoJoNz1E3WMF5DWrOt5XV9tIRXZVccJurA4PvjP+thuwF2wISaNPfujv9RVVCsGT3p34TGbUq/wO2hqwo7ws7KL4CnlJ/1zSbsWkGuJcWQ+U3be7XJjgyZoG8HRD3cDhy4wiTMVYpwdOQD3MES8gMj3pTp0Q0ijtLH/MqJAPBN5oFocQ7kRw94GBhP+hyugTapfZp/ZQ9FAX4ZcZ+W1CBX1PLWaiCKPrtTWhYBQSnlRvAfe2gxqYBczKBuIq4=
  - secure: KmKk/nE+PtLX20/lPXWAhoiB83+hnNtvo5wMM1rDrEBp3JCzZTJvTZrHMy5eRrLkaIZOHA6yZ8w70hqlC9Co4BEDoc39hxodH+jPeNutPvV6i/tbADxfG1Ta1+B6tEec5CCpQxdjHzmCMZKOEbXQTK5OifR3uuYtuvTZRWSH4/iGkWN4U3t8hxX2zTd5bKbeE+DJ57WdPu/Bp/P4BK6qkFxQo5n2Vev/uTRx1wRHgRKRBnwahahkxf62+K+Sd+Pk6nv3eQ9M6k3XgeusESDVJZK6spMHcy56PIXYzPpb1ydcRyIHdpKZ1gqTAJxUCEhELTntk5T9pScAHlOy1KH6imtfUWEC9PpM5uF7vfLK+9xm+sLuCHv3DiRAuzFoH4EM2OL7pKp9L7GABdCHtpSP9ghQip1RmoVvi/D7rNme6u/Pv9CCijpOp5reY76YQIcByvKRdWY3sg0w8GCDDs9n2vBELGpjK28i888zSpceNNQ1zW0opP8qGrCfxWRW84NFu6jw2xA6DFRe4AqdKZPxfxL88RWoda/ZIe6OlyhQFK0J1dljK0faynx9moqRXDgvIaEyo0kXiDdD+o07WSRxaNONM2BdlT7ByGpv/9hbPY/FHyE66wj+I+qo0JtixOMHvlsDS8ggoW1POT4IJVJosvmCDXBxosZ8bpPVs0c/AH4=
  - secure: KKPrbVQiJP7e9CZu+NbPuypuVLcE5SQBCcmoC7/rAjxAtldFILAdGC8dJ0dpqisOomk/9c586OqgK1u9pDwrXg95CbamqMxtYqqTIjmKQd3+M8LOTuMRl/Cufc6y7XYEI6fP6zTzQqtR7tvTvAfPszcpRi/PJrEZLy5SGMFkUlfloz1DTWQuWmRye3/tA6eyGW1eZxNDu7eNNC+o2AxioyobCiZA2/BJDYGE57M43vTDQn/eP/XGxjOycVp9k3j4vbDdsTFWB/u5x+1QKLm8JHD64QrpvDy4hu0UKJ6pyGrBvnmu8TM1swr8tCrREXWXB4S8AtEblS9oKnA53Ne/TAAcrltGXhBRxbzICU/p4CXo3VMo1i8T0OXOkVwcrEr7l85GFjQjKMJpSkYQ5AeP/yf3Ge0vUz9XdLZ1aRSC80GQPnwNGvORuH4Gv0CLgFImjkej7kzjwszsS1sqxBQfKUow3D0cRpblhtGIIzvuZ5nlN1W4ZjGfnIehDcxvxMJK4eOGyzvOhDCGM8MJjAYJ8CIcZ95sUvVaBsLaDaDxTR742DNto6Ark4DogmoYMDi/Oz3h7anuwSP/b67Qilas19y9m/vTNEWHqyGxChlLbKwGnvyFkq2somIJtrqRh5goZXmp+23UaW2VkamG00r0aybWy0gcqdAY0+bZO4EInTs=
